language: node_js
sudo: required

# branches:
#   only:
#     - master

services:
  - docker

install:
  - npm install

jobs:
  include:
    - stage: test
      name: "Unit Tests: Node 6"
      node_js: 6

      before_install:
        - docker pull ansi/mosquitto
        - docker run -d -p 1883:1883 -l mosquitto ansi/mosquitto
        - docker pull mongo
        - docker run -d -p 27017:27017 -l mongodb mongo
        - docker pull rabbitmq
        - docker run -d -p 5672:5672   -l rabbitmq rabbitmq

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 8"
      node_js: 8

      before_install:
        - docker pull ansi/mosquitto
        - docker run -d -p 1883:1883 -l mosquitto ansi/mosquitto
        - docker pull mongo
        - docker run -d -p 27017:27017 -l mongodb mongo
        - docker pull rabbitmq
        - docker run -d -p 5672:5672   -l rabbitmq rabbitmq

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 10"
      node_js: 10

      before_install:
        - docker pull ansi/mosquitto
        - docker run -d -p 1883:1883 -l mosquitto ansi/mosquitto
        - docker pull mongo
        - docker run -d -p 27017:27017 -l mongodb mongo
        - docker pull rabbitmq
        - docker run -d -p 5672:5672   -l rabbitmq rabbitmq

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Documentation Tests"
      node_js: 10

      script:
        - npm run lint:md
        - npm run lint:text
